from urllib.parse import urlencode

LAPIS_URL = "https://lapis-virus4.loculus.org/influenza-a/sample/"
DIAMOND_DB_URL = "https://loculus-project.github.io/diamond-reference-databases/results/influenza-a/diamond.dmnd"
DATASET_SERVER = "https://data.clades.nextstrain.org/v3"
GS_DATASET_SERVER = "https://raw.githubusercontent.com/genspectrum/nextclade-datasets/flu/data"
dataset_name_map = {
    "seg1": {
        "h1n1pdm": "nextstrain/flu/h1n1pdm/pb2",
        "h1n1": "nextstrain/flu/h1n1/pb2",
        "h3n2": "nextstrain/flu/h3n2/pb2",
        "h2n2": "nextstrain/flu/h2n2/pb2",
    },
    "seg2": {
        "h1n1pdm": "nextstrain/flu/h1n1pdm/pb1",
        "h1n1": "nextstrain/flu/h1n1/pb1",
        "h3n2": "nextstrain/flu/h3n2/pb1",
        "h2n2": "nextstrain/flu/h2n2/pb1",
    },
    "seg3": {
        "h1n1pdm": "nextstrain/flu/h1n1pdm/pa",
        "h1n1": "nextstrain/flu/h1n1/pa",
        "h3n2": "nextstrain/flu/h3n2/pa",
        "h2n2": "nextstrain/flu/h2n2/pa",
    },
    "seg4": {
        "h1_h1n1pdm": "nextstrain/flu/h1n1pdm/ha/CY121680",
        "h1_h1n1": "nextstrain/flu/h1n1/ha",
        "h3_h3n2": "nextstrain/flu/h3n2/ha/CY163680",
        "h2_h2n2": "nextstrain/flu/h2n2/ha",
        "h3_h3n8": "flu/HA/ha_h3_h3n8/CY028836",
        "h4_h4n6": "flu/HA/ha_h4_h4n6/CY181241",
        "h5_h5n1": "community/moncla-lab/iav-h5/ha/all-clades",
        "h5_h5n2": "flu/HA/ha_h5_h5n2/KU143256",
        "h6_h6n2": "flu/HA/ha_h6_h6n2/CY130030",
        "h7_h7n9": "flu/HA/ha_h7_h7n9/NC_026425.1",
        "h8_h8n4": "flu/HA/ha_h8_h8n4/CY136131",
        "h9_h9n2": "flu/HA/ha_h9_h9n2/NC_004908.1",
        "h10_h10n7": "flu/HA/ha_h10_h10n7/CY136094",
        "h11_h11n9": "flu/HA/ha_h11_h11n9/CY130070",
        "h12_h12n5": "flu/HA/ha_h12_h12n5/CY130078",
        "h13_h13n6": "flu/HA/ha_h13_h13n6/CY130086",
        "h14_h14n5": "flu/HA/ha_h14_h14n5/JN696314",
        "h15_h15n9": "flu/HA/ha_h15_h15n9/CY006010",
        "h16_h16n3": "flu/HA/ha_h16_h16n3/CY136630",
        "h17_h17n10": "flu/HA/ha_h17_h17n10/CY103876",
        "h18_h18n11": "flu/HA/ha_h18_h18n11/CY125945"
    },
    "seg5": {
        "h1n1pdm": "nextstrain/flu/h1n1pdm/np",
        "h1n1": "nextstrain/flu/h1n1/np",
        "h3n2": "nextstrain/flu/h3n2/np",
        "h2n2": "nextstrain/flu/h2n2/np",
    },
    "seg6": {
        "n1_h1n1pdm": "nextstrain/flu/h1n1pdm/na/MW626056",
        "n1_h1n1": "nextstrain/flu/h1n1/na",
        "n2_h3n2": "nextstrain/flu/h3n2/na/EPI1857215",
        "n2_h2n2": "nextstrain/flu/h2n2/na",
        "n1_h5n1": "flu/NA/na_n1_h5n1/NC_007361.1",
        "n2_h6n2": "flu/NA/na_n2_h6n2/CY130032",
        "n2_h9n2": "flu/NA/na_n2_h9n2/NC_004909.1",
        "n2_h5n2": "flu/NA/na_n2_h5n2/KU143347",
        "n3_h16n3": "flu/NA/na_n3_h16n3/CY136632",
        "n4_h8n4": "flu/NA/na_n4_h8n4/CY136133",
        "n5_h12n5": "flu/NA/na_n5_h12n5/CY130080",
        "n6_h4n6": "flu/NA/na_n6_h4n6/CY181243",
        "n6_h13n6": "flu/NA/na_n6_h13n6/CY130088",
        "n7_h10n7": "flu/NA/na_n7_h10n7/CY136096",
        "n8_h3n8": "flu/NA/na_n8_h3n8/CY028838",
        "n9_h7n9": "flu/NA/na_n9_h7n9/NC_026429.1",
        "n9_h11n9": "flu/NA/na_n9_h11n9/CY130072",
        "n9_h15n9": "flu/NA/na_n9_h15n9/CY005407",
        "n10_h17n10": "flu/NA/na_n10_h17n10/CY103878",
        "n11_h18n11": "flu/NA/na_n11_h18n11/CY125947"
    },
    "seg7": {
        "h1n1pdm": "nextstrain/flu/h1n1pdm/mp",
        "h1n1": "nextstrain/flu/h1n1/mp",
        "h3n2": "nextstrain/flu/h3n2/mp",
        "h2n2": "nextstrain/flu/h2n2/mp",
    },
    "seg8": {
        "h1n1pdm": "nextstrain/flu/h1n1pdm/ns",
        "h1n1": "nextstrain/flu/h1n1/ns",
        "h3n2": "nextstrain/flu/h3n2/ns",
        "h2n2": "nextstrain/flu/h2n2/ns",
    },
}

datasets_in_gs_server = {
    "seg4": {
        "h3_h3n8", "h4_h4n6", "h5_h5n2", "h6_h6n2", "h7_h7n9", "h8_h8n4", "h9_h9n2", "h10_h10n7", "h11_h11n9", "h12_h12n5", "h13_h13n6", "h14_h14n5", "h15_h15n9", "h16_h16n3", "h17_h17n10", "h18_h18n11"
    },
    "seg6": {
        "n1_h5n1", "n2_h6n2", "n2_h9n2", "n2_h5n2", "n3_h16n3", "n4_h8n4", "n5_h12n5", "n6_h4n6", "n6_h13n6", "n7_h10n7", "n8_h3n8", "n9_h7n9", "n9_h11n9", "n9_h15n9", "n10_h17n10", "n11_h18n11"
    }
}

SEGMENTS = ["seg4", "seg6"]
wildcard_constraints:
    segment = r"seg\d+"

def build_filter(segment):
    params = [
        ("dataUseTerms", "OPEN"),
        ("segments", ",".join(f"{segment}-{subtype}"for subtype in dataset_name_map[segment].keys())),
        ("versionStatus", "LATEST_VERSION"),
        ("isRevocation", "false"),
        (f"length_{segment}From", "100"),
        # ("hostNameScientific", "Homo sapiens"),
    ]

    return urlencode(params)


def fasta_url(wildcards):
    filter_string = build_filter(wildcards.segment)
    return (
        f"{LAPIS_URL}unalignedNucleotideSequences"
        f"?downloadAsFile=true"
        f"&downloadFileBasename=influenza-a_nuc-{wildcards.segment}_2026-03-16T1639"
        f"&fastaHeaderTemplate=%7BaccessionVersion%7D"
        f"&{filter_string}"
    )


rule all:
    input:
        expand("results/diamonddifferences_{segment}.tsv", segment=SEGMENTS),
        expand("results/sortdifferences_{segment}.tsv", segment=SEGMENTS)


rule download_sequences:
    output:
        fasta="results/segment_{segment}.fasta",
    params:
        url=fasta_url,
    shell:
        """
        curl -L "{params.url}" -o {output.fasta}
        """


rule align:
    input:
        sequences="results/segment_{segment}.fasta",
    output:
        results="results/aligned_{segment}_{subtype}.tsv",
    params:
        dataset_server=lambda w: GS_DATASET_SERVER if w.subtype in datasets_in_gs_server.get(w.segment, set()) else DATASET_SERVER,
        dataset_name=lambda w: dataset_name_map[w.segment][w.subtype],
    shell:
        """
        nextclade run \
            {input.sequences} \
            --output-tsv {output.results} \
            --server {params.dataset_server} \
            --dataset-name {params.dataset_name} \
        """


rule process_alignments:
    input:
        results=lambda w: expand(
            "results/aligned_{segment}_{subtype}.tsv",
            segment=w.segment,
            subtype=dataset_name_map[w.segment].keys(),
        ),
        script="parse_alignment_output.py",
    output:
        merged="results/nextclade_{segment}.tsv",
    params:
        segment_paths=lambda w: " ".join(
            f"--alignment-results results/aligned_{w.segment}_{subtype}.tsv"
            for subtype in dataset_name_map[w.segment].keys()
        ),
    shell:
        """
        python {input.script} \
            {params.segment_paths} \
            --output {output.merged}
        """

rule run_diamond:
    input:
        sequences="results/segment_{segment}.fasta",
        diamond_db="diamond.dmnd",
    output:
        diamond_output="results/diamond_{segment}.tsv",
    shell:
        """
        diamond blastx \
            --query {input.sequences} \
            --db {input.diamond_db} \
            --out {output.diamond_output} \
            --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore
        """


rule nextclade_sort:
    input:
        sequences="results/segment_{segment}.fasta",
        minimizer="minimizer.json",
    output:
        results="results/sort_{segment}.tsv",
    shell:
        """
        nextclade sort -m {input.minimizer} \
        -r {output.results}  {input.sequences} \
        --max-score-gap 0.3 --min-score 0.05 --min-hits 2  --all-matches
        """


rule find_sort_differences:
    input:
        sort_output="results/sort_{segment}.tsv",
        alignment_results="results/nextclade_{segment}.tsv",
        script="find_sort_differences.py",
    output:
        differences="results/sortdifferences_{segment}.tsv",
    shell:
        """
        python {input.script} \
            --sort {input.sort_output} \
            --alignment {input.alignment_results} \
            --output {output.differences}
        """


rule find_diamond_differences:
    input:
        diamond_output="results/diamond_{segment}.tsv",
        alignment_results="results/nextclade_{segment}.tsv",
        script="find_diamond_differences.py",
    output:
        differences="results/diamonddifferences_{segment}.tsv",
    shell:
        """
        python {input.script} \
            --diamond {input.diamond_output} \
            --alignment {input.alignment_results} \
            --output {output.differences}
        """
